name: cross-systems-template

services:
  dev:
    build:
      context: image/
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.13.12
      tags:
        - cross-systems-template-image:latest
        - cross-systems-template-image:${APP_VERSION:-v1.1}
    image: cross-systems-template-image:latest
    container_name: dev
    security_opt:
      - "seccomp=unconfined"
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    restart: unless-stopped
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command:
      [
        "sh",
        "-lc",
        '/venv/bin/python -m pytest -s tests/python/test_pycuda.py && tail -f /dev/null',
      ]
    working_dir: /opt/project
    volumes:
      - .:/opt/project
    ports:
      - "9080:9080"
      - "9001:9001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, graphics, utility, video]
